resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
steps:
- script: docker login -u $(dockerId) -p $(pswd) teamulapacr.azurecr.io
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    azureSubscription: AzureDevOps
    azureContainerRegistry: teamulapacr.azurecr.io
- task: Docker@1
  displayName: 'Push an image'
  inputs:
    azureSubscription: AzureDevOps
    azureContainerRegistry: teamulapacr.azurecr.io
    command: 'Push an image'





