resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
steps:
- script: docker build -t $(dockerId).azurecr.io/$(dockerImage) .
- script: |
    docker login -u $(dockerId).azurecr.io -p $(pswd) $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(dockerImage)






