# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'c4tschallenge:$(build.buildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    azureSubscriptionEndpoint: AzureDevOps
    azureContainerRegistry: teamulapacr.azurecr.io
- task: Docker@1
  displayName: 'Push an image'
  inputs:
    azureSubscriptionEndpoint: AzureDevOps
    azureContainerRegistry: teamulapacr.azurecr.io
    command: 'Push an image'

